### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by macsc** [sabidib/remarking#16]
# Bug Report

**remarking version:**

**Current behavior:**

Works:
`remarking help`
ANY Invocation of a request to download highlights in any format doesn't
`remarking run json --token <mytoken> books` 
json, csv, table

**Expected behavior:**

Successful completion of any command requesting an export in any format of highlights from my Remarkable Library

**Steps to reproduce:**

$ remarking persist csv Finished
Extractors: remarkable
Collections: Finished
✔ Connected to RM cloud.
[=== ] Retrieving cloud metadataTraceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/remarking/cli/cli.py", line 36, in _wrapper
    return main_command_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/remarking/cli/writer_command_runner.py", line 110, in command
    documents, highlights = extract.run_extract(
  File "/usr/local/lib/python3.9/site-packages/remarking/cli/extract.py", line 58, in run_extract
    documents, highlights = app.run_app(working_directory, collection_names)
  File "/usr/local/lib/python3.9/site-packages/remarking/cli/app.py", line 43, in run_app
    document_metadata = self._get_cloud_document_metadata(collection_names)
  File "/usr/local/lib/python3.9/site-packages/remarking/cli/app.py", line 118, in _get_cloud_document_metadata
    folder_objects = self._rmcloud.get_folders(collection_names)
  File "/usr/local/lib/python3.9/site-packages/remarking/rmcloud.py", line 70, in get_folders
    items = self.get_meta_items()
  File "/usr/local/lib/python3.9/site-packages/remarking/rmcloud.py", line 62, in get_meta_items
    return self._api_client.get_meta_items()
  File "/usr/local/lib/python3.9/site-packages/rmapy/api.py", line 180, in get_meta_items
    for item in response.json():
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/remarking", line 8, in <module>
    sys.exit(command_line())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/remarking/cli/cli.py", line 39, in _wrapper
    raise FileBugExceptionWrapper from exc
remarking.cli.cli.FileBugExceptionWrapper: If you have run into an exception during normal usage please copy the exeption and then file a bug here: https://github.com/sabidib/remarking/issues/new/choose

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by jantoebes** [comment]
Doesnt work anymore with the new api

There is some progress updating rmapy (a library that is used) 

https://github.com/subutux/rmapy/pull/26
