### ISSUE TITLE
Bug: Can't extract anymore

### ISSUE THREAD

**Issue by bkamaleson** [sabidib/remarking#18]
I used this last in March 11th.

I'm aware that there has been API issues,( [rmapy:new API](https://github.com/subutux/rmapy/pull/26) ) but I thought it was fixed since the comments for the API issue were around July 2021 and this was working for me in March 2022. 

Is there an alternative for extracting highlighted texts from PDFs and EPUBs?

Thanks,
Clay

$ remarking run csv -o highlights "Beyond Traditional Credit Analysis"

Extractors: remarkable
Collections: Beyond Traditional Credit Analysis
✔ Connected to RM cloud.
[ ===] Retrieving cloud metadataTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/cli.py", line 36, in _wrapper
    return main_command_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
[  ==] Retrieving cloud metadata    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/writer_command_runner.py", line 110, in command
    documents, highlights = extract.run_extract(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/extract.py", line 58, in run_extract
    documents, highlights = app.run_app(working_directory, collection_names)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/app.py", line 43, in run_app
    document_metadata = self._get_cloud_document_metadata(collection_names)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/app.py", line 118, in _get_cloud_document_metadata
    folder_objects = self._rmcloud.get_folders(collection_names)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/rmcloud.py", line 70, in get_folders
    items = self.get_meta_items()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/rmcloud.py", line 62, in get_meta_items
    return self._api_client.get_meta_items()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rmapy/api.py", line 180, in get_meta_items
    for item in response.json():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/remarking", line 8, in <module>
    sys.exit(command_line())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/cli.py", line 39, in _wrapper
    raise FileBugExceptionWrapper from exc
remarking.cli.cli.FileBugExceptionWrapper: If you have run into an exception during normal usage please copy the exeption and then file a bug here: https://github.com/sabidib/remarking/issues/new/choose

**Comment by bkamaleson** [comment]
# Bug Report

**remarking version:** 0.1.4



**Current behavior:**  remarking run csv -o highlights "Beyond Traditional Credit Analysis"



**Expected behavior:** 
Extractors: remarkable
Collections: Beyond Traditional Credit Analysis
Connecting to RM cloud
Connected to RM cloud.
Retrieving cloud metadata
Downloading documents
Downloading "Beyond Traditional Credit Analysis"
Downloaded 1 documents.
Running extractors on documents
Running extractor "RemarkableHighlightExtractor" on "Beyond Traditional Credit Analysis"
Ran extractors and found 366 highlights, 366 are new.



**Steps to reproduce:** remarking run csv -o highlights "Beyond Traditional Credit Analysis"



**Related code:**

Extractors: remarkable
Collections: Beyond Traditional Credit Analysis
✔ Connected to RM cloud.
[ ===] Retrieving cloud metadataTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/cli.py", line 36, in _wrapper
    return main_command_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
[  ==] Retrieving cloud metadata    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/writer_command_runner.py", line 110, in command
    documents, highlights = extract.run_extract(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/extract.py", line 58, in run_extract
    documents, highlights = app.run_app(working_directory, collection_names)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/app.py", line 43, in run_app
    document_metadata = self._get_cloud_document_metadata(collection_names)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/app.py", line 118, in _get_cloud_document_metadata
    folder_objects = self._rmcloud.get_folders(collection_names)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/rmcloud.py", line 70, in get_folders
    items = self.get_meta_items()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/rmcloud.py", line 62, in get_meta_items
    return self._api_client.get_meta_items()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rmapy/api.py", line 180, in get_meta_items
    for item in response.json():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/remarking", line 8, in <module>
    sys.exit(command_line())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/remarking/cli/cli.py", line 39, in _wrapper
    raise FileBugExceptionWrapper from exc
remarking.cli.cli.FileBugExceptionWrapper: If you have run into an exception during normal usage please copy the exeption and then file a bug here: https://github.com/sabidib/remarking/issues/new/choose




```
insert short code snippets here
```

**Other information:**

**Comment by nonoesp** [comment]
Hi, all! Same error happening here. ✋

**Comment by pschitte** [comment]
I also have the same error!

**Comment by brandonkboswell** [comment]
Same error happening for me as well
